[package]
name = "podders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "49.0.0"
flatbuffers = "23.5.26"
uuid = { version = "1.6.1", features = ["v4"] }
